Update api-governance-validate.yml

diff --git a/.github/workflows/api-governance-validate.yml b/.github/workflows/api-governance-validate.yml
--- a/.github/workflows/api-governance-validate.yml
+++ b/.github/workflows/api-governance-validate.yml
@@ -74,11 +74,18 @@ jobs:
           echo "$response"
           echo "$status_code"
 
+          # Check if the error message exists in the response
+          if [[ "$response" == *"Spec does not conform with Ruleset"* ]]; then
+            echo "Validation failed: Spec does not conform with Ruleset"
+            exit 1  # Exit with a non-zero code to indicate failure
+          fi
+
+
           # Extracting and displaying relevant information using jq
-          actual=$(echo "$response" | jq -r '.[0].doc:encodes[0].conforms[0].trace[0].traceValue.actual')
-          expected=$(echo "$response" | jq -r '.[0].doc:encodes[0].conforms[0].trace[0].traceValue.expected')
-          resultMessage=$(echo "$response" | jq -r '.[0].doc:encodes[0].conforms[0].result[0].resultMessage')
-          resultSeverity=$(echo "$response" | jq -r '.[0].doc:encodes[0].conforms[0].result[0].resultSeverity')
+          actual=$(echo "$response" | jq -r '.[0] | .["doc:encodes"][0]["conforms"][0]["trace"][0]["traceValue"]["actual"]')
+          expected=$(echo "$response" | jq -r '.[0] | .["doc:encodes"][0]["conforms"][0]["trace"][0]["traceValue"]["expected"]')
+          resultMessage=$(echo "$response" | jq -r '.[0] | .["doc:encodes"][0]["conforms"][0]["result"][0]["resultMessage"]')
+          resultSeverity=$(echo "$response" | jq -r '.[0] | .["doc:encodes"][0]["conforms"][0]["result"][0]["resultSeverity"]')
 
           echo "Actual: $actual"
           echo "Expected: $expected"
