Update api-governance-validate.yml

diff --git a/.github/workflows/api-governance-validate.yml b/.github/workflows/api-governance-validate.yml
--- a/.github/workflows/api-governance-validate.yml
+++ b/.github/workflows/api-governance-validate.yml
@@ -22,8 +22,8 @@ jobs:
       - name: Checkout Repository
         uses: actions/checkout@v2
 
-      # - name: Install jq
-      #   run: sudo apt-get install jq
+      - name: Install jq
+        run: sudo apt-get install jq
           
       - name: Install api-catalog cli
         run: |
@@ -69,9 +69,24 @@ jobs:
           echo "Constructed URL: $URL"
           
           response=$(anypoint-cli-v4 governance api validate --client_id=$ANYPOINT_CLIENT_ID --client_secret=$ANYPOINT_CLIENT_SECRET --organization=$ANYPOINT_ORG $URL --remote-rulesets 68ef9520-24e9-4cf2-b2f5-620025690913/https-enforcement/1.1.1 --remote)
-           status_code=$(echo "${response: -3}") # Extracting the status code from the response
+          status_code=$(echo "${response: -3}") # Extracting the status code from the response
 
-          if [ $status_code -gt 399 ]; then
-            echo "Anypoint login failed"
-            exit 1
+          echo "$response"
+          echo "$status_code"
+
+          # Extracting and displaying relevant information using jq
+          actual=$(echo "$response" | jq -r '.[0] | .["doc:encodes"][0]["conforms"][0]["trace"][0]["traceValue"]["actual"]')
+          expected=$(echo "$response" | jq -r '.[0] | .["doc:encodes"][0]["conforms"][0]["trace"][0]["traceValue"]["expected"]')
+          resultMessage=$(echo "$response" | jq -r '.[0] | .["doc:encodes"][0]["conforms"][0]["result"][0]["resultMessage"]')
+          resultSeverity=$(echo "$response" | jq -r '.[0] | .["doc:encodes"][0]["conforms"][0]["result"][0]["resultSeverity"]')
+
+          echo "Actual: $actual"
+          echo "Expected: $expected"
+          echo "Result Message: $resultMessage"
+          echo "Result Severity: $resultSeverity"   
+
+          # Check if the error message exists in the response
+          if [[ "$response" == *"Spec does not conform with Ruleset"* ]]; then
+            echo "Validation failed: Spec does not conform with Ruleset"
+            exit 1  # Exit with a non-zero code to indicate failure
           fi
