Update api-governance-validate.yml

diff --git a/.github/workflows/api-governance-validate.yml b/.github/workflows/api-governance-validate.yml
--- a/.github/workflows/api-governance-validate.yml
+++ b/.github/workflows/api-governance-validate.yml
@@ -56,32 +56,6 @@ jobs:
           npm i -g anypoint-cli-v4
           anypoint-cli-v4 plugins:install anypoint-cli-governance-plugin      
 
-      - name: API Governance - HTTPS Validate
-        run: |
-
-          asset_id=$ASSET_ID
-          version=$VERSION
-          
-          echo "$asset_id"
-          echo "$version"
-
-          # Construct the URL
-          URL=$ANYPOINT_ORG/$asset_id/$version
-
-          echo "Constructed URL: $URL"
-          
-          response=$(anypoint-cli-v4 governance api validate --client_id=$ANYPOINT_CLIENT_ID --client_secret=$ANYPOINT_CLIENT_SECRET --organization=$ANYPOINT_ORG $URL --remote-rulesets 68ef9520-24e9-4cf2-b2f5-620025690913/https-enforcement/1.1.1 --remote)
-          status_code=$(echo "${response: -3}") # Extracting the status code from the response
-
-          echo "$response"
-          echo "$status_code"
-
-          # Check if the error message exists in the response
-          if [[ "$response" == *"Spec does not conform with Ruleset"* ]]; then
-            echo "Validation failed: Spec does not conform with Ruleset"
-            exit 1  # Exit with a non-zero code to indicate failure
-          fi
-
       - name: API Governance - Open API Specification Validate
         run: |
 
@@ -97,6 +71,32 @@ jobs:
           echo "Constructed URL: $URL"
           
           response=$(anypoint-cli-v4 governance api validate --client_id=$ANYPOINT_CLIENT_ID --client_secret=$ANYPOINT_CLIENT_SECRET --organization=$ANYPOINT_ORG $URL --remote-rulesets 68ef9520-24e9-4cf2-b2f5-620025690913/openapi-best-practices/1.1 --remote)
+          status_code=$(echo "${response: -3}") # Extracting the status code from the response
+
+          echo "$response"
+          echo "$status_code"
+
+          # Check if the error message exists in the response
+          if [[ "$response" == *"Spec does not conform with Ruleset"* ]]; then
+            echo "Validation failed: Spec does not conform with Ruleset"
+            exit 1  # Exit with a non-zero code to indicate failure
+          fi
+      
+      - name: API Governance - HTTPS Validate
+        run: |
+
+          asset_id=$ASSET_ID
+          version=$VERSION
+          
+          echo "$asset_id"
+          echo "$version"
+
+          # Construct the URL
+          URL=$ANYPOINT_ORG/$asset_id/$version
+
+          echo "Constructed URL: $URL"
+          
+          response=$(anypoint-cli-v4 governance api validate --client_id=$ANYPOINT_CLIENT_ID --client_secret=$ANYPOINT_CLIENT_SECRET --organization=$ANYPOINT_ORG $URL --remote-rulesets 68ef9520-24e9-4cf2-b2f5-620025690913/https-enforcement/1.1.1 --remote)
           status_code=$(echo "${response: -3}") # Extracting the status code from the response
 
           echo "$response"
