Update pub-api-to-flex-gw.yml

diff --git a/.github/workflows/pub-api-to-flex-gw.yml b/.github/workflows/pub-api-to-flex-gw.yml
--- a/.github/workflows/pub-api-to-flex-gw.yml
+++ b/.github/workflows/pub-api-to-flex-gw.yml
@@ -125,33 +125,33 @@ jobs:
 
           
 
-      - name: Apply policy
-        run: |
-          api_response=$(cat api-response | jq -r '.id')
-          echo "${api_response}"
+      # - name: Apply policy
+      #   run: |
+      #     api_response=$(cat api-response | jq -r '.id')
+      #     echo "${api_response}"
           
-          login_response=$(cat login-response | jq -r '.access_token')
+      #     login_response=$(cat login-response | jq -r '.access_token')
       
-          status_code=$(curl -s -w "%{http_code}" -o /dev/null --location --request POST "https://anypoint.mulesoft.com/apimanager/api/v1/organizations/$ANYPOINT_ORG/environments/$ANYPOINT_ENVIRONMENT/apis/${api_response}/policies" \
-            --header "Authorization: Bearer $login_response" \
-            --header "Content-Type: application/json" \
-            --data '{
-              "configurationData": {
-                "username": "user",
-                "password": "test"
-              },
-              "pointcutData": null,
-              "assetId": "http-basic-authentication",
-              "assetVersion": "1.3.1",
-              "groupId": "68ef9520-24e9-4cf2-b2f5-620025690913"
-            }')
+      #     status_code=$(curl -s -w "%{http_code}" -o /dev/null --location --request POST "https://anypoint.mulesoft.com/apimanager/api/v1/organizations/$ANYPOINT_ORG/environments/$ANYPOINT_ENVIRONMENT/apis/${api_response}/policies" \
+      #       --header "Authorization: Bearer $login_response" \
+      #       --header "Content-Type: application/json" \
+      #       --data '{
+      #         "configurationData": {
+      #           "username": "user",
+      #           "password": "test"
+      #         },
+      #         "pointcutData": null,
+      #         "assetId": "http-basic-authentication",
+      #         "assetVersion": "1.3.1",
+      #         "groupId": "68ef9520-24e9-4cf2-b2f5-620025690913"
+      #       }')
       
-          echo "Command output: $status_code"
+      #     echo "Command output: $status_code"
       
-          if [ $status_code -gt 399 ]; then
-            echo "Error occurred while trying to apply Basic Auth Policy to the API instance"
-            exit 1
-          fi
+      #     if [ $status_code -gt 399 ]; then
+      #       echo "Error occurred while trying to apply Basic Auth Policy to the API instance"
+      #       exit 1
+      #     fi
 
       - name: Deploy API
         run: |
