Update pub-api-to-flex-gw.yml

diff --git a/.github/workflows/pub-api-to-flex-gw.yml b/.github/workflows/pub-api-to-flex-gw.yml
--- a/.github/workflows/pub-api-to-flex-gw.yml
+++ b/.github/workflows/pub-api-to-flex-gw.yml
@@ -19,9 +19,9 @@ jobs:
 
     steps:
 
-      - name: Check Condition and Exit
-        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
-        run: exit 78  # Use an exit code to terminate the workflow without running subsequent steps
+      # - name: Check Condition and Exit
+      #   if: github.event_name == 'push' && github.ref == 'refs/heads/main'
+      #   run: exit 78  # Use an exit code to terminate the workflow without running subsequent steps
 
       - name: Checkout Repository
         uses: actions/checkout@v2
@@ -53,32 +53,32 @@ jobs:
           echo "ASSET_ID=$asset_id" >> $GITHUB_ENV
           echo "VERSION=$version" >> $GITHUB_ENV
 
-      - name: Install anypoint-cli-v4 cli
-        run: |
-          npm i -g anypoint-cli-v4
-          anypoint-cli-v4 plugins:install anypoint-cli-governance-plugin      
+      # - name: Install anypoint-cli-v4 cli
+      #   run: |
+      #     npm i -g anypoint-cli-v4
+      #     anypoint-cli-v4 plugins:install anypoint-cli-governance-plugin      
 
-      - name: API Governance
-        run: |
+      # - name: API Governance
+      #   run: |
 
-          asset_id=$ASSET_ID
-          version=$VERSION
+      #     asset_id=$ASSET_ID
+      #     version=$VERSION
           
-          echo "$asset_id"
-          echo "$version"
+      #     echo "$asset_id"
+      #     echo "$version"
 
-          # Construct the URL
-          URL=$ANYPOINT_ORG/$asset_id/$version
+      #     # Construct the URL
+      #     URL=$ANYPOINT_ORG/$asset_id/$version
 
-          echo "Constructed URL: $URL"
+      #     echo "Constructed URL: $URL"
           
-          response=$(anypoint-cli-v4 governance api validate --client_id=$ANYPOINT_CLIENT_ID --client_secret=$ANYPOINT_CLIENT_SECRET --organization=$ANYPOINT_ORG $URL --remote-rulesets 68ef9520-24e9-4cf2-b2f5-620025690913/https-enforcement/1.1.1 --remote)
-           status_code=$(echo "${response: -3}") # Extracting the status code from the response
+      #     response=$(anypoint-cli-v4 governance api validate --client_id=$ANYPOINT_CLIENT_ID --client_secret=$ANYPOINT_CLIENT_SECRET --organization=$ANYPOINT_ORG $URL --remote-rulesets 68ef9520-24e9-4cf2-b2f5-620025690913/https-enforcement/1.1.1 --remote)
+      #      status_code=$(echo "${response: -3}") # Extracting the status code from the response
 
-          if [ $status_code -gt 399 ]; then
-            echo "Anypoint login failed"
-            exit 1
-          fi
+      #     if [ $status_code -gt 399 ]; then
+      #       echo "Anypoint login failed"
+      #       exit 1
+      #     fi
           
       - name: Anypoint login
         run: |
@@ -130,33 +130,33 @@ jobs:
 
           
 
-      # - name: Apply policy
-      #   run: |
-      #     api_response=$(cat api-response | jq -r '.id')
-      #     echo "${api_response}"
+      - name: Apply policy
+        run: |
+          api_response=$(cat api-response | jq -r '.id')
+          echo "${api_response}"
           
-      #     login_response=$(cat login-response | jq -r '.access_token')
+          login_response=$(cat login-response | jq -r '.access_token')
       
-      #     status_code=$(curl -s -w "%{http_code}" -o /dev/null --location --request POST "https://anypoint.mulesoft.com/apimanager/api/v1/organizations/$ANYPOINT_ORG/environments/$ANYPOINT_ENVIRONMENT/apis/${api_response}/policies" \
-      #       --header "Authorization: Bearer $login_response" \
-      #       --header "Content-Type: application/json" \
-      #       --data '{
-      #         "configurationData": {
-      #           "username": "user",
-      #           "password": "test"
-      #         },
-      #         "pointcutData": null,
-      #         "assetId": "http-basic-authentication",
-      #         "assetVersion": "1.3.1",
-      #         "groupId": "68ef9520-24e9-4cf2-b2f5-620025690913"
-      #       }')
+          status_code=$(curl -s -w "%{http_code}" -o /dev/null --location --request POST "https://anypoint.mulesoft.com/apimanager/api/v1/organizations/$ANYPOINT_ORG/environments/$ANYPOINT_ENVIRONMENT/apis/${api_response}/policies" \
+            --header "Authorization: Bearer $login_response" \
+            --header "Content-Type: application/json" \
+            # --data '{
+            #   "configurationData": {
+            #     "username": "user",
+            #     "password": "test"
+            #   },
+              "pointcutData": null,
+              "assetId": "external-oauth2-access-token-enforcement",
+              "assetVersion": "1.5.1",
+              "groupId": "68ef9520-24e9-4cf2-b2f5-620025690913"
+            }')
       
-      #     echo "Command output: $status_code"
+          echo "Command output: $status_code"
       
-      #     if [ $status_code -gt 399 ]; then
-      #       echo "Error occurred while trying to apply Basic Auth Policy to the API instance"
-      #       exit 1
-      #     fi
+          if [ $status_code -gt 399 ]; then
+            echo "Error occurred while trying to apply Basic Auth Policy to the API instance"
+            exit 1
+          fi
 
       - name: Deploy API
         run: |
